<p><a href="<?php echo $this->url(
    array(
        'controller' => 'sales',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Sign Our Guestbook</a></p>
 
Guestbook Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt>ID Sales - <?php echo $this->escape($entry->id) ?></dt>
    <dd>ID Product -<?php echo $this->escape($entry->product) ?></dd>
    <?php endforeach ?>
</dl>