<script>
function proximaPagina(){
	let page = document.getElementById('page');
	page.value = Number.parseInt(page.value)+1;
	return true;
}

function primeiraPagina(){
	let page = document.getElementById('page');
	page.value = 1;
	return true;
}

function ultimaPagina(){
	let page = document.getElementById('page');
	let qtdRegistros = document.getElementById('qtdRegistros');
	page.value = 80000000-Number.parseInt(qtdRegistros);
	return true;
}


function paginaAnterior(){
	let page = document.getElementById('page');
	page.value = Number.parseInt(page.value)-1;
	return true;
}
</script>
<br /><br />
<div id="view-content">
	 
<?php
	$this->form->setAction($this->url());
	echo $this->form; 
?>
<dl>
	<?php 
	echo 'Tempo Execução Apenas consulta em milissegundos -> '. $this->timeDB;
	echo '<br/>Tempo Execução Total em milissegundos -> '. $this->time;
	?>
	<hr/>
	<?php
		if($this->entries != null){

			foreach ($this->entries as $entry): ?>
		<dt>ID Sales - <?php echo $this->escape($entry->id) ?></dt>
		<dd>ID Product -<?php echo $this->escape($entry->product) ?></dd>
		<?php 
		// if($entry->customerName != ''){?>
		<dd>CustomerName -<?php echo $this->escape($entry->CustomerName) ?></dd>
		<?php	
		// }
		?>
			<?php endforeach; 
		}
		?>
</dl>
</div>